apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: exposeconfigs.network.deinstapel.de
spec:
  conversion:
    strategy: None
  group: network.deinstapel.de
  names:
    kind: ExposeConfig
    listKind: ExposeConfigList
    plural: exposeconfigs
    singular: exposeconfig
    shortNames:
    - ec
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name:  kingress
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kingress
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["network.deinstapel.de"]
  resources: ["exposeconfigs"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kingress
subjects:
- kind: ServiceAccount
  name: kingress
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kingress

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kingress
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kingress
  template:
    metadata:
      labels:
        app: kingress
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      serviceAccountName: kingress
      automountServiceAccountToken: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: kingress
        image: deinstapel/kingress:v2
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
