apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: exposeconfigs.network.deinstapel.de
spec:
  conversion:
    strategy: None
  group: network.deinstapel.de
  names:
    kind: ExposeConfig
    listKind: ExposeConfigList
    plural: exposeconfigs
    singular: exposeconfig
    shortNames:
    - ec
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
